### ISSUE TITLE
Static data for Health and Education UI returned from client-side endpoint

### ISSUE THREAD

**Issue by sutjin** [ProjectDrawdown/global-research-platform#101]
Time Estimate: 6 hours

As an Engineer, I would like to have static data returned from the API when opening the Health and Education Dashboard

Requirement;
* Dataset converted from the Health and Education sheet

**Comment by eethann** [comment]
@sutjin is this ready for @shrutimehta13 to review?

**Comment by eethann** [comment]
@sutjin is this ready for @shrutimehta13 to review?

**Comment by colleenskemp** [comment]
QA for this has been completed. Tracked in other tickets.
