### ISSUE TITLE
Researcher can see population data for all years for each REF scenario

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform#108]
Researcher can see the data for the population scenarios chosen in a table on the population settings page. 

**Acceptance Criteria:**
* Population scenario data should show for all years in each population model. 
* Should show for each of the two population scenarios: REF1 (current projection) and REF2 (with health and education population)
* Should change when a different population scenario is chosen for either REF1 or REF2

**Comment by eethann** [comment]
@shrutimehta13 has this completed QA?

**Comment by shrutimehta13** [comment]
@colleenskemp Population data is available under Health & Education. 
All tables show data as per excel sheet https://docs.google.com/spreadsheets/d/16-5LT39ElpYS3st0y9vR7b3vxOBBRRCI/edit?skip_itp2_check=true#gid=1194660297

1. Naming conventions need to be checked for Heading and report name (varies from design)
2. %change reports also not implemented as shown in design and in excel sheet
<img width="648" alt="Screenshot 2021-11-24 at 5 16 14 PM" src="https://user-images.githubusercontent.com/34771314/143233365-f0667528-7489-40fe-9e30-1c65acbb30d7.png">
<img width="1216" alt="Screenshot 2021-11-24 at 5 15 44 PM" src="https://user-images.githubusercontent.com/34771314/143233382-6cec4d6e-f748-4e65-9ce4-64e0603aaa53.png">
