### ISSUE TITLE
Regression Testing - Electricity Generation Sector

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#123]
Need: We have to do a check of the electricity generation sector to make sure we haven't broken anything resulting from the last round of work. 

Please conduct regression testing for the electricity generation sector.

**Comment by eethann** [comment]
I suspect these issues are independent of the H&E UI, but are still notable. First is a "should have", the upload button also looks off in alignment, the period of the lifetimes savings graph is a must fix.

**Comment by eethann** [comment]
Moved to #130 , #131 , and #132 

Closing this ticket.
