### ISSUE TITLE
Heading is cut off for calculation outputs data table

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#125]
Steps to replicate: 

1) Create workbook and add water heating solution
2) Select help button in results table

"CALCULATION OUTPUTS AND INTEGRATION DATA TABLES" heading is cut off. 

Testing location: 13 inch mac book pro/ chrome

<img width="1280" alt="Screen Shot 2021-11-15 at 10 49 07 AM" src="https://user-images.githubusercontent.com/20732309/141821736-6aa5e1c7-4f5b-48d0-82d4-64bf33796235.png">

**Comment by eethann** [comment]
@sutjin is this ready for @shrutimehta13 to review?
