### ISSUE TITLE
Design QA: All expected tables and components are reflected with pleasing look & feel

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#126]
Link to design: https://www.figma.com/file/LJl7Q9ffgq3TycEEltY98K/Health-and-Education-UI?node-id=53%3A4586

This is a catch-all ticket requesting a check that all they key blocks/ components are present. These charts will likely not match design, but should be there and looking good. Please use your judgement if something is not looking right or good to you. Please create tickets for design improvements as you see a need. 

1) Navigation drawer https://www.figma.com/file/LJl7Q9ffgq3TycEEltY98K/Health-and-Education-UI?node-id=53%3A4585
Navigation drawer should have the same behavior as before. The only special thing is that it has links to the population and emissions factors tables. 

2) Population table: https://www.figma.com/file/LJl7Q9ffgq3TycEEltY98K/Health-and-Education-UI?node-id=53%3A4586

3) Emissions factor table: https://www.figma.com/file/LJl7Q9ffgq3TycEEltY98K/Health-and-Education-UI?node-id=53%3A4752

2) Solution cluster (TAM, assumptions, results, outputs) - https://www.figma.com/file/LJl7Q9ffgq3TycEEltY98K/Health-and-Education-UI?node-id=53%3A4918
To see on staging, select help icon next to results table. 

See video of Nabil's overview: https://drive.google.com/drive/u/1/folders/1p1LJVu2F4VT3UuG9NKrMYBluucJ9D1w-

**Comment by shrutimehta13** [comment]
Navigation drawer has links to Population and Emission factors. Pl check following points  @colleenskemp @sutjin  for ticket closure. Let me know if i should create new tickets

1. Some tables missing in both as compared to design.  (marked)
2. Naming convention of emission reports also vary as compared to design  (marked)
<img width="1440" alt="Screenshot 2021-11-22 at 4 39 50 PM" src="https://user-images.githubusercontent.com/34771314/142855917-58db4cf3-bdc4-478d-996b-98af625a005a.png">

<img width="1440" alt="Screenshot 2021-11-22 at 4 40 09 PM" src="https://user-images.githubusercontent.com/34771314/142855893-51b04ef2-0493-4ebc-92c1-3dd303c77620.png">

3. Compared values displayed in tables from excel sheet where available. Not possible for some like electricity generation. could not verify the following as values were blank in https://docs.google.com/spreadsheets/d/16-5LT39ElpYS3st0y9vR7b3vxOBBRRCI/edit#gid=775774068
<img width="1235" alt="Screenshot 2021-11-22 at 5 57 02 PM" src="https://user-images.githubusercontent.com/34771314/142862229-d8a56769-8b66-4084-89a2-9385635a35cb.png">
<img width="1244" alt="Screenshot 2021-11-22 at 5 52 51 PM" src="https://user-images.githubusercontent.com/34771314/142862252-02e98be5-aed2-49c8-9b14-4686092ff495.png">

**Comment by eethann** [comment]
I think this is best assigned to @chadfrisch or @MamtaMehra to review with actual data. Assigning to @sutjin to take a first pass at confirming. The initial wireframes were not made with full data.
