### ISSUE TITLE
QA - Confirm TAM Mix is correct across solutions

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#128]
Please ensure TAM Mix table items are correct across solutions. 

Compare population sheet: https://docs.google.com/spreadsheets/d/16-5LT39ElpYS3st0y9vR7b3vxOBBRRCI/edit?usp=sharing&ouid=116246822588517777536&rtpof=true&sd=true

with 

Staging: https://stage.pdd.colab.coop (create your own test workbook)

Check the following solutions: 
* electricity
* space heating
* space cooling
* water heating
* clean cook stove
* com light
* res light

Here is Nabil's run-through for reference: https://drive.google.com/drive/u/1/folders/1p1LJVu2F4VT3UuG9NKrMYBluucJ9D1w-

**Comment by shrutimehta13** [comment]
tested TAM MIX items for solutions mentioned. They are correctly included with correct % as mentioned in https://docs.google.com/spreadsheets/d/16-5LT39ElpYS3st0y9vR7b3vxOBBRRCI/edit?skip_itp2_check=true#gid=1229988975

Integration (Include in Conventional/Ignore) default was correct for all except Space heating. Please check if it needs attention. else the ticket can be closed @colleenskemp 
<img width="1280" alt="Screenshot 2021-11-22 at 6 02 39 PM" src="https://user-images.githubusercontent.com/34771314/142867910-83da531d-f359-401e-ab16-1e21a64d0374.png">

**Comment by eethann** [comment]
Assigning to @sutjin to review and confirm.

**Comment by colleenskemp** [comment]
This is looking correct to me. Closing ticket.
