### ISSUE TITLE
Res Light and Com light graphs displaying error in clusters view

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#136]
Issue: 
Both res light and com light are showing the same error in their graph: 

1) No data is shown on the graph
2) The y axis is cut off

<img width="1280" alt="Screen Shot 2021-12-06 at 10 41 08 AM" src="https://user-images.githubusercontent.com/20732309/144886053-b94f3dfa-81b5-49ca-b4a1-125e37893867.png">

**Comment by sutjin** [comment]
Data has beenf ixed @colleenskemp please refer to the new worksheet that Mamta has sent via email for verification
