### ISSUE TITLE
Code Documentation for Web UI 

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform#14]
Initialize documentation system and commit initial documentation of existing code.

Documentation should cover:

* All components, their properties, related state objects, and usage notes.
* API methods
* Redux stores, thunks, and reducers
* Higher order components (e.g. form data bindings) and their intent and example usage
* Directory structure and code organization

It might also include developer documentation and component styleguides, depending on the solution chosen. These are not necessary for this ticket, though, and might be independent of the code docs.

**Comment by eethann** [comment]
documentation.js is probably the slickest and quickest approach, using jsdoc with sensible default configuration and optional custom md doc files in the nav

styleguidist is a nice alternative to storybook and great for documenting components, but does not seem to easily include non-component code (except as md)

**Comment by eethann** [comment]
https://react-styleguidist.js.org/docs/getting-started

**Comment by litenull** [comment]
This would be the first of the README.md

## Coding guide

Brief introduction to the project.


### Files

```
|\_\_\_\_components  - all the components of the app
|\_\_\_\_stories - storybook stories for components of the app
|\_\_\_\_theme - theme variables for spacing, colors, breakpoints (taken from carbon design system)
|\_\_\_\_images - the images of the app
|\_\_\_\_redux - reducers, actions, ...
|\_\_\_\_util - utilities
```


### Prerequisites

- Node. We recommend installing via [Node Version Manager](https://github.com/nvm-sh/nvm#installing-and-updating). Run `nvm use` to install the working node version. 

### Installation

1. Copy `.env.example` to `.env` and modify as needed: `cp .env.example .env` (for details, see the **Environment Variables** section below)
2. Install dependencies: `npm install`
3. Make sure your `HOST` environment variable is unset, or set to `localhost`.
4. Start the server: `npm start`
5. You should now be able to visit your local front-end at http://localhost:3000/

Optionally,

1. If you want to explore the app in [Storybook](https://storybook.js.org/): `npm run storybook`

### Styling

In terms of styling, we use [styled-components](https://github.com/styled-components/styled-components) and [chakra](https://chakra-ui.com/).

### App Router

```
/
/auth/:provider
/login
/logout

/workbook
/workbook/:id
/workbook/:id/clone
/workbook/:id/postclone

/workbook/:id/portfolio/edit
/workbook/:id/technologies/:technologyId

```

### CI/CD

- Merge into `develop` branch to view on staging server
- Merge into `master` branch to view on production server

### Troubleshooting

### Environment Variables
	
* `REACT_APP_API_URL=127.0.0.1` = API URL

**Comment by litenull** [comment]
Notes:
- Document redux using UML flow
- Add components that are theme to a specific folder
