### ISSUE TITLE
Developer documentation for the Web UI

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform#15]
**Time Estimate:** 

Update developer docs in the web ui.

Should include

- [ ] overview of app and overall system architecture

- [ ] code standards and linter configurations

- [ ] process for forking and making pull requests

- [ ] summary of code organization and structure

[]community standards (code of conduct, etc.)

**Comment by eethann** [comment]
Nice examples from mapbox gl lib: https://github.com/mapbox/mapbox-gl-js/blob/main/CONTRIBUTING.md

**Comment by colleenskemp** [comment]
We are out of budget to do further work on this during this phase.
