### ISSUE TITLE
Work book header is overlapping on some screen sizes

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#26]
Time Estimate: 2 hours

Problem: Overlapping header and project details for some screen sizes. Tested on (2560 x 1600) size screen. (13 inch mac).

Description: 
<img width="1280" alt="Screen Shot 2021-06-14 at 7 59 48 AM" src="https://user-images.githubusercontent.com/20732309/121896110-8de3e800-cce6-11eb-973f-485ec13bf346.png">

Acceptance Criteria: 
There should be no overlapping text in header on standard desktop screens.

Additional Notes: 
This application is not yet tailored to small or medium screen sizes. Most users will be viewing from desktop initially.

**Comment by colleenskemp** [comment]
@Chukslord1 - Please add time estimate for this ticket after you've had a chance to look at it with @litenull

**Comment by Chukslord1** [comment]
@colleenskemp  Time Estimate: 2 Hours

**Comment by shrutimehta13** [comment]
Will work on most popular desktop sizes. Issue will start to appear at different viewports across browsers Like on 
Mac Safari on < 1280px, 
Mac Chrome on <1250px
Mac FF on <1290px

so, Issue will appear for eg on older MacBook 1280x800. @colleenskemp please take action. Popular desktop statistics for ref 
<img width="827" alt="Screenshot 2021-07-26 at 10 17 57 PM" src="https://user-images.githubusercontent.com/34771314/127028108-383385e8-5b55-45e8-a17f-5ef55bb4685b.png">

**Comment by shrutimehta13** [comment]
on browser widths <1600px (most desktops)
<img width="909" alt="Screenshot 2021-11-25 at 6 03 40 PM" src="https://user-images.githubusercontent.com/34771314/143442793-848e1049-a82d-40fb-874f-9d8ebf66b037.png">
