### ISSUE TITLE
Disable run button while calculation is running

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform#32]
Time estimate: 

Problem: Currently a user can initiate multiple simultaneous calculation requests by clicking the run button multiple times while it's spinning. 

Acceptance criteria: The run button should be disabled for clicks while a calculation is running.

**Comment by BrianAlderman** [comment]
Resolved here: https://github.com/ProjectDrawdown/global-research-platform/pull/74
Unable to link PR to this issue for some reason 🤷
