### ISSUE TITLE
Migrate codebase to a new repo for application with 2 subfolders for API and UI

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#35]
Need: Simplify the project for open source contributor by having the App code to be in one project (UI and API) and able to run it easily by following through the documentation

Acceptance criteria:
- Migrated the UI project into a `/ui` directory
- Migrated the Solutions API code into a `/api` directory
- Root directory to have comprehensive readme on how to run the project
- Able to run all depenedncy via Docker

**Comment by sutjin** [comment]
Added code to convert Solutions repo into a library as discussed:
https://github.com/ProjectDrawdown/solutions/pull/269

initial pull request for structure:
https://github.com/ProjectDrawdown/global-research-platform/pull/36

**Comment by sutjin** [comment]
Finalize build:
https://github.com/ProjectDrawdown/global-research-platform/pull/38
