### ISSUE TITLE
When I edit my workbook, I see my solutions above unselected solutions shown with opacity

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#40]
Problem: 
A visual distinction is needed during the editing process between solutions which have already been selected as part of my solution set and solutions which have not.  

See design here: https://www.figma.com/file/QImAyi1guE4AICGMN7uODK/Drawdown-Portfolio-UI-Figma-Chakra-UI?node-id=1550%3A16993

![Edit workbook](https://user-images.githubusercontent.com/20732309/124778131-5a236900-df06-11eb-9786-941d23bb2824.png)

Acceptance criteria: 
As a user, when I am editing my portfolio, I see my selected solutions shown above unselected solutions. Unselected solutions display with opacity.

**Comment by gyermich** [comment]
we just opened a PR for #46, it seems to be related to this one - @janeenault  and I could take this one as well
