### ISSUE TITLE
Header for Workbook Overview Page

### ISSUE THREAD

**Issue by brodavi** [ProjectDrawdown/global-research-platform#44]
https://www.figma.com/file/QImAyi1guE4AICGMN7uODK/Drawdown-Portfolio-UI-Figma-Chakra-UI?node-id=1971%3A122156

![Solution Set Overview](https://user-images.githubusercontent.com/1271493/124785844-d325bf00-df0c-11eb-87ef-9684fdb8feb8.png)

The header should include the following elements: 

    The calculated state of the run button in the top right corner

    Blue bar

    Author name

    About/ description

    Created date (optional - nice to have) - can close without

    workbook name displays at top of page

**Comment by brodavi** [comment]
The calculated run button is all that is missing here.

**Comment by sutjin** [comment]
https://github.com/ProjectDrawdown/global-research-platform/pull/72
