### ISSUE TITLE
Implement API endpoint to upload resource files

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform#54]
Time Estimate: 10 hours

Allow users to upload arbitrary resource files and store them in the database. Should accept both Adoption and Market projection CVSs.

Extend the `/vma_csv` endpoint concept as a model, but for `POST /resource/{entity}`.

Requirements:

- [ ] Does not currently need to pass this data to the solutions API, just accept, store, and list in future lists of that resource entity type.

**Comment by sutjin** [comment]
PR Opened, but topics for open dicussion is written on the PR

https://github.com/ProjectDrawdown/global-research-platform/pull/58
