### ISSUE TITLE
As a user, I can mark resources or workbooks as either public or private

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#78]
Estimate: 5 hours

Problem: Users need to be able to share the resources they contribute or workbooks they create. 

Details/ acceptance criteria: 
As a user, I should be able to indicate private or public when I create a workbook OR contribute to the resource library. This may be a contribution of a new adoption source, VMA, or TAM.  

Additional Note: 
This is the lowest level of resource sharing and publishing required by our SOW agreement

**Comment by sutjin** [comment]
PR Opened https://github.com/ProjectDrawdown/global-research-platform/pull/88
